stages:
  - build

build_project:
  stage: build
  script:
    - formulaName="url-helper-app"
    - packageName="${CI_PROJECT_NAME:?}"
    - signIdentity="3rd Party Mac Developer Installer: Grigorii Entin (465NA5BW7E)"
    - ./Pods/GEContinuousIntegration/Scripts/build-gitlab-cmd "$PWD/build" "${packageName:?}" "${formulaName:?}" "${signIdentity:?}"
  artifacts:
    paths:
      - build/*.pkg
      - build/*.dmg
      - build/Formula/*.rb
  tags:
    - xcode-10
    - macos
