# yamllint disable rule:truthy
# yamllint disable-line rule:document-start
name: URLHelperApp

targets:
  URLHelperApp:
    type: application
    platform: macOS
    deploymentTarget: '12.0'
    sources:
      - path: URLHelperApp
      - path: URLHelperApp/AppBundleIdentifierAndURLForURL
        buildPhase: resources
    settings:
      CODE_SIGN_ENTITLEMENTS: URLHelperApp/URLHelperApp.entitlements
      INFOPLIST_PREPROCESS: YES
      INFOPLIST_OTHER_PREPROCESSOR_FLAGS: -CC
    scheme: {}
    dependencies: []

options:
  bundleIdPrefix: com.grigorye
  postGenCommand: ./XcodeGen/postGen

settings:
  MARKETING_VERSION: '0.1'
  DEVELOPMENT_TEAM: 465NA5BW7E

  CURRENT_PROJECT_VERSION: '$(BUNDLE_VERSION)'
  GENERATE_INFOPLIST_FILE: YES

  # Overridden for CI runs:
  BUNDLE_VERSION: Local

packages: {}
