#! /bin/bash

# This script defines the rules/acts like a matcher between an url and the corresponding application that is used to open the url.
# Feel free to modify it as necessary/replace it with something more appropriate.

set -x
set -euo pipefail

url="$1"
shift

v1Resolver=~/Library/Application\ Scripts/com.grigorye.URLHelperApp/AppBundleIdentifierForURL

if test -f "$v1Resolver"; then
	appBundleIdentifier=$("$v1Resolver" "$url")
	echo '{"finalURL": "'"$url"'", "appBundleIdentifier": "'"$appBundleIdentifier"'" }'
	exit
fi

# Process redirects before making the "routing" decision.
redirectedURL=$(curl -Ls -o /dev/null -w '%{url_effective}' "$url" || echo "$url")

# Here were route.
case "$redirectedURL" in
#'https://stackoverflow.com/'*)
#	echo "org.epichrome.app.Coding"
#	;;
*)
	echo '{"finalURL": "'"$redirectedURL"'", "appBundleIdentifier": "com.google.Chrome" }'
	;;
esac
