#! /bin/sh

set -x
set -euo pipefail

wd=$(dirname "$0")

bundle exec pod install
mint run xcodeprojFixUUIDs *.xcodeproj
cp "$wd"/xcworkspace-addons/dot-xcodesamplecode.plist *.xcworkspace/.xcodesamplecode.plist
